USE Medico
GO

DROP PROCEDURE uspComboFormaFarmaceutica;
GO

CREATE PROCEDURE uspComboFormaFarmaceutica
AS
BEGIN
	SELECT IIDFORMAFARMACEUTICA as Id, NOMBRE
	FROM FormaFarmaceutica
	WHERE BHABILITADO = 1;
END

EXEC uspComboFormaFarmaceutica;
GO

CREATE PROCEDURE uspListarMedicamentos
AS
BEGIN
	SELECT IIDMEDICAMENTO, NOMBRE, CONCENTRACION, PRECIO, STOCK
	FROM Medicamento
	WHERE BHABILITADO = 1;
END
GO

EXEC uspListarMedicamentos
GO

DROP PROCEDURE uspConsultarMedicamentosPorFormaFarmaceutica;
GO

CREATE PROCEDURE uspConsultarMedicamentosPorFormaFarmaceutica
@IIDFORMAFARMACEUTICA INT
AS
BEGIN
	SELECT IIDMEDICAMENTO, NOMBRE, CONCENTRACION, PRECIO, STOCK, IIDFORMAFARMACEUTICA
	FROM Medicamento
	WHERE BHABILITADO = 1 AND IIDFORMAFARMACEUTICA = @IIDFORMAFARMACEUTICA;
END
GO

EXEC uspConsultarMedicamentosPorFormaFarmaceutica 1
GO