USE Medico;

SELECT * FROM Clinica;
SELECT IIDCLINICA, NOMBRE, DIRECCION
	FROM Clinica
	WHERE BHABILITADO = 1;
GO

--CREATE PROCEDURE uspListarEspecialidades
--AS
--BEGIN
--SELECT IIDESPECIALIDAD, NOMBRE, DESCRIPCION
--	FROM Especialidad
--	WHERE BHABILITADO = 1;
--END

EXEC uspListarEspecialidades;